### ISSUE TITLE
CallBack event for Crosshair 

### ISSUE THREAD

**Issue by supriyakhankarnw18** [tradingview/lightweight-charts-android#47]
Hi team,
       I’m using lightweight chart inside CollapsingToolbarLayout, because of which CrossHairLine vertical drag is messing with CollapsingToolbarLayout Scroll, is there any solution for this Or   Is there any Callbacks available through which we can detect that crosshair is on or off. So I can disable and enable the  CollapsingToolbarLayout Scroll.

Thanks

**Comment by makedonsky94** [comment]
Hi! We can make gesture detector for that case. The next version will include the fix.

At the moment there is no public methods or gesture detectors in the library that covering the case you describe

**Comment by supriyakhankarnw18** [comment]
Okay, thanks. when will the gesture detector be available?

**Comment by makedonsky94** [comment]
We've made a new interface `TouchDelegate`. You can check the example of usage [here](https://github.com/tradingview/lightweight-charts-android/blob/master/app/src/main/java/com/tradingview/lightweightcharts/example/app/view/pager/NestedScrollDelegate.kt).
Also, [here](https://github.com/tradingview/lightweight-charts-android/blob/master/app/src/main/java/com/tradingview/lightweightcharts/example/app/view/pager/ViewPagerActivity.kt) the example of screen with scrollable view.

The main reason why we didn't make a universal touch detector is because it would take too long to implement the logic which will cover every case. So we've decided to make a custom handler that will provide easiest access to detector of touches. At the moment you should implement the logic by yourself that will cover your cases. 

If you want to disable collapsing of toolbar when user is interacting with crosshair then you can disable intercepting of touches by parent after long tap event (see [requestDisallowInterceptTouchEvent](https://developer.android.com/reference/android/view/ViewParent#requestDisallowInterceptTouchEvent(boolean))) and enable again after some time (ex create a timer for 2 sec and recreate it after any touch event).

If these solution is not enough for your case please let us know.
