### ISSUE TITLE
Showing white screen on back press of fragment transition In the latest version also (v3.5.0)

### ISSUE THREAD

**Issue by supriyakhankarnw18** [tradingview/lightweight-charts-android#68]
Hi team, 
we are facing the same issue in the latest version(v3.5.0)   

Previously reported issue link below
https://github.com/tradingview/lightweight-charts-android/issues/57

issue details:-
white screen issue over chart view when replacing a fragment on the back press and navigating to the previous chart fragment.

Sharing code snippets which have been used for fragment transaction which is shared in the sample app, here we only added backStack line .addToBackStack("tag"), also shared a video reference.

private fun <T : Fragment> startFragment(fragmentClass: Class<T>) { supportFragmentManager .beginTransaction() .replace( R.id.fragment_container_fl, FragmentFactory.getInstance(fragmentClass) ) .addToBackStack("tag") .commit() }

https://user-images.githubusercontent.com/70312717/128698974-50b32b1c-ee01-40c9-886b-3d84a232eb45.mp4

**Comment by makedonsky94** [comment]
Hi! I think we misunderstood your last issue. 
As I see you get not just the white screen but empty chart. You can see black line at the bottom of the screen. It is happening because of wrong usage of fragment API. Please, check [the official documentation](https://developer.android.com/guide/fragments/lifecycle). After restoring of the fragment there will be no calls of onCreate method. So if you want to use backstack, set observing model to onViewCreated method of lifecycle or later

**Comment by supriyakhankarnw18** [comment]
Hi! I have tried to do the same way you suggest. but it's still not working 

sharing the code screenshot 
please let me know if anything missing 
![Uploading Screenshot 2021-08-09 at 6.07.35 PM.png…]()

**Comment by makedonsky94** [comment]
Yep, as you can see chartApi is lazy object. It means the object will be in the memory while the fragment in memory. So after recreating of view you should update links to ChartApi.
If you have problems with understanding of fragments API, we can make an example of backstack usage

**Comment by supriyakhankarnw18** [comment]
@makedonsky94  yes. An example will be more helpful
